### ISSUE TITLE
Unable to edit content

### ISSUE THREAD

**Issue by paulroberts68** [BCDevExchange/devex#130]
Gov user signed in and created an opportunity for an unpublished program and project. They saved their work and then tried to edit both Program, Project and Opportunity. When in edit mode, the form fields were blank thus they are unable to update their content.

**Comment by mark-a-wilson** [comment]
I _think_ I just experienced the same issue as Paul...

- On PROD, as Admin, I added admin access to my account (Mark Wilson) for [this opportunity](https://bcdevexchange.org/opportunityadmin/opp-notifying-bcdx-users-that-new-opportunities-have-been-posted1/edit) which had been created by Paul. 
- I signed out and signed back in as Mark Wilson
- Navigating to that opportunity to edit it, I saw the 'Admin' badge and could click 'Edit', but after clicking Edit, saw the following (all existing content lost, etc.):

![screen shot 2017-03-09 at 9 39 58 am](https://cloud.githubusercontent.com/assets/16946297/23762892/64032e76-04ac-11e7-912b-f99f70c79c40.png)

Here's what the console says:

`TypeError: Cannot read property '_id' of undefined
    at new <anonymous> (https://bcdevexchange.org/dist/application-fc070d2d54.min.js:24:5644)
    at Object.instantiate (https://bcdevexchange.org/lib/angular/angular.min.js:42:109)
    at https://bcdevexchange.org/lib/angular/angular.min.js:91:374
    at Object.<anonymous> (https://bcdevexchange.org/lib/angular-ui-router/release/angular-ui-router.min.js:7:23742)
    at https://bcdevexchange.org/lib/angular/angular.min.js:16:71
    at sa (https://bcdevexchange.org/lib/angular/angular.min.js:82:244)
    at n (https://bcdevexchange.org/lib/angular/angular.min.js:68:6)
    at g (https://bcdevexchange.org/lib/angular/angular.min.js:59:428)
    at https://bcdevexchange.org/lib/angular/angular.min.js:59:67
    at https://bcdevexchange.org/lib/angular/angular.min.js:64:67 <ui-view>
(anonymous) @ angular.min.js:119`
